const data = {
  products: [
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: "high quality product",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 160,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 30,
      countInStock: 46,
      description: "high quality product",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Fcuk",
      rating: 4.0,
      numReviews: 10,
      countInStock: 16,
      description: "high quality product",
    },
    {
      name: "Causal Shirt",
      slug: "causal-shirt",
      category: "Shirts",
      image: "/images/shirt4.jpeg",
      price: 95,
      brand: "Reymond",
      rating: 3.8,
      numReviews: 60,
      countInStock: 30,
      description: "high quality product",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 20,
      brand: "Oliver",
      rating: 4.3,
      numReviews: 10,
      countInStock: 26,
      description: "high quality product",
    },
    {
      name: "fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 100,
      brand: "Zara",
      rating: 4.3,
      numReviews: 12,
      countInStock: 40,
      description: "high quality product",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 50,
      brand: "Casely",
      rating: 3.7,
      numReviews: 100,
      countInStock: 12,
      description: "high quality product",
    },
    {
      name: "Causal Pants",
      slug: "causal-pants",
      category: "Pants",
      image: "/images/pants4.jpg",
      price: 200,
      brand: "Reymond",
      rating: 4.6,
      numReviews: 16,
      countInStock: 20,
      description: "high quality product",
    },
  ],
};

export default data;